services:
  fastapi:
    build: .
    image: 192.168.2.1:5000/course_app:latest
    container_name: course_app_container
    volumes:
      - ./course_app:/app/course_app
    ports:
      - "8004:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
