version: "3.9"
services:
  myapp:
    environment:
      JEKYLL_UID: 1000
      JEKYLL_GID: 1000
      JEKYLL_ENV: production
    build: .
    ports: 
      - "3333:3333"
    restart_policy:
        condition: on-failure
    deploy:
      replicas: 3