http {
    include /etc/nginx/mime.types;
    index index.html index.htm;
    server {
        root /www/data/;
        listen 3333;
        location = /health {
           access_log off;
           default_type text/plain;
           return 200 "OK\n";
        }

        location / {
           try_files $uri $uri.html $uri/ /index.html;
        }
    }
}

events { }