# Use an official Python runtime as a parent image
FROM python:3.12.1-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Define environment variable
ENV PORT=8000

# Create a directory to store the certs and copy them
# RUN mkdir /certs
# COPY /etc/letsencrypt/live/search.kevsrobots.com /certs

# Run app.py when the container launches
# CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--ssl-keyfile=/certs/privkey.pem", "--ssl-certfile=/certs/fullchain.pem"]

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
