version: '3.8'

services:
  fastapi-app:
    image: search:latest  # Use the image from Docker registry
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - .:/usr/src/app
    