/**
 * Social card injector for KevsRobots Projects Hub.
 *
 * Cloudflare Worker route: www.kevsrobots.com/projects/*
 *
 * If the request is from a known social/preview crawler AND the path
 * matches `/projects/<owner>/<slug>` (no extra path segments, no
 * query-string id), fetch a pre-rendered OG card from the projects API
 * and return it. Otherwise pass through to origin so humans see the
 * normal JS-rendered SPA.
 *
 * The OG HTML itself is generated by the projects-api endpoint
 *   GET https://projects.kevsrobots.com/og/<owner>/<slug>
 * which must be deployed before this worker is useful.
 */

const OG_API_BASE = 'https://projects.kevsrobots.com';

// Matches /projects/<owner>/<slug> with optional trailing slash, where
// owner and slug are URL-safe and don't contain dots or slashes. Excludes
// known sub-routes (hub, search, my-projects, staff-picks, editor.html,
// view.html, etc.) which all contain dots, dashes-in-the-rightmost-segment
// covered by content of <slug>, OR are single-segment under /projects/.
// The two-segment `/projects/<a>/<b>` shape is uniquely a project URL.
const PROJECT_PATH_RE = /^\/projects\/([^\/]+)\/([^\/]+)\/?$/;

// Crawlers that read OG tags but don't execute JS. Sourced from the
// public user-agent strings each platform documents. Case-insensitive.
const CRAWLER_UA_RE = new RegExp([
  'twitterbot',
  'facebookexternalhit',
  'facebookcatalog',
  'slackbot-linkexpanding',
  'slackbot',
  'discordbot',
  'linkedinbot',
  'whatsapp',
  'telegrambot',
  'mastodon',
  'pleroma',
  'akkoma',
  'misskey',
  'iframely',
  'embedly',
  'redditbot',
  'pinterest',
  'snapchat',
  'vkshare',
  'applebot',
  'bingpreview',
  'skypeuripreview',
  'flipboard',
  'tumblr',
  'bitlybot',
  'nuzzel',
  'qwantify',
  'outbrain',
  'yandex',
  'baiduspider',
  'duckduckbot',
].join('|'), 'i');

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const match = url.pathname.match(PROJECT_PATH_RE);
    if (!match) return fetch(request);

    const ua = request.headers.get('User-Agent') || '';
    if (!CRAWLER_UA_RE.test(ua)) return fetch(request);

    const [, owner, slug] = match;
    const ogUrl = `${OG_API_BASE}/og/${encodeURIComponent(owner)}/${encodeURIComponent(slug)}`;

    try {
      const resp = await fetch(ogUrl, {
        cf: { cacheTtl: 300, cacheEverything: true },
        headers: { 'User-Agent': 'kevsrobots-og-worker/1.0' },
      });
      // Pass through the API's response (including 404 with its own
      // generic OG card). Force text/html so the crawler reads it.
      const body = await resp.text();
      return new Response(body, {
        status: resp.status,
        headers: {
          'Content-Type': 'text/html; charset=utf-8',
          'Cache-Control': 'public, max-age=300',
          'X-OG-Worker': 'hit',
        },
      });
    } catch (err) {
      // On any API error, fall through to origin so the crawler at
      // least gets the 404 SPA — better than a 5xx from us.
      return fetch(request);
    }
  },
};
