FROM alpine:latest AS getfiles
# install git
# RUN apk --no-cache add git
# RUN mkdir /src
# WORKDIR /src
# RUN git clone https://www.github.com/kevinmcaleer/kevsrobots.com

FROM jekyll/jekyll:4.2.0 as jekyll
RUN gem install webrick
# COPY --from=getfiles /src/kevsrobots.com/web /src
# WORKDIR /src
# RUN mkdir -p /src/_site
# RUN mkdir -p .jekyll-cache _site
RUN jekyll serve --watch --livereload --incremental
