version: "3.9"
services:
  kevsrobots-dev:
    environment:
      JEKYLL_UID: 1000
      JEKYLL_GID: 1000
      JEKYLL_ENV: production
    build: .
    restart: always
    ports: 
      - 4000:4000
      - 35729:35729
    volumes:
      - ../../web:/srv/jekyll
    # command: "jekyll serve --watch --livereload"
  
    command: "jekyll serve /srv/jekyll --watch --livereload --host 0.0.0.0"
    

   