version: "3.9"
services:
  jekyll-serve:
    image: jekyll/jekyll
    environment:
      JEKYLL_UID: 1000
      JEKYLL_GID: 1000
      JEKYLL_ENV: development
    # build: .
    # restart: always
    volumes:
      - '../../web:/srv/jekyll'
    ports:
      - 4000:4000
      - 35729:35729
    # command: "jekyll serve --watch --livereload --iterative"
    command: "jekyll serve --watch --livereload"
   