FROM alpine:latest AS getfiles
# install git
RUN echo 'grabing hostname'
RUN echo 'hostname='$HOSTNAME >> _config.yml
RUN cat _config.yml
# RUN echo "installing git"
# RUN apk --no-cache add git
RUN echo "making /src"
RUN mkdir /src
# WORKDIR /src
# RUN echo "cloning kevsrobots"
# RUN git clone https://www.github.com/kevinmcaleer/kevsrobots.com --recurse-submodules --remote-submodules

FROM ruby:3.1.3  as jekyll
RUN apt-get update \ 
   && apt-get install -y \
   python3-pygments \
   && apt-get clean \
   && rm -rf /var/lib/apt/lists/*

RUN gem install \
  github-pages \
  jekyll \
  jekyll-redirect-from \
  kramdown \
  rdiscount \
  rouge

# COPY --from=getfiles /src/kevsrobots.com/web /src
# WORKDIR /src
RUN mkdir -p /src/_site
# COPY --from=youtube /yt/youtube/youtube.yaml /src/_data/youtube.yaml
# RUN jekyll build 

# FROM nginx
# COPY --from=getfiles /src/kevsrobots.com/stacks/kevsrobots/nginx.conf /etc/nginx/nginx.conf
# COPY --from=jekyll /src/_site /www/data

# RUN chown -R nginx:nginx /www/data
# RUN chmod -R 755 /www/data/*
# RUN echo 'hostname='$HOSTNAME >> /www/data/_config.yml
# RUN jekyll serve /srv/jekyll --watch --livereload --incremental --host
# RUN cd /srv/jekyll
WORKDIR /srv/jekyll