title: KevsRobots
email: kevinmcaleer@gmail.com
description: This is the official website of Kevin McAleer
baseurl: ""
url: "https://www.kevsrobots.com"

markdown: kramdown
permalink: /blog/:title:output_ext

kramdown:
  toc_levels: 1..6

plugins:
  - jekyll-redirect-from
  # - jekyll-toc

# Compression settings for production
# TEMPORARILY DISABLED - may be breaking footer
# compress_html:
#   clippings: all
#   comments: all
#   endings: all
#   startings: []
#   blanklines: false
#   profile: false

# Environment-specific settings
environment: production

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

collections:
  rooms:
    output: true
    permalink: /museum/:collection/:name
  ptor:
    output: true
    permalink: /ptor/:name.html
  # robots:
  #   output: true
  #   permalink: /robots/:name.html
  reviews:
    output: true
    permalink: /reviews/:name.html
  how_it_works:
    output: true
    permalink: /resources/how_it_works/:name.html
  code_liberry:
    output: true
    permalink: /code_liberry/:name.html
  boards:
    output: true
    permalink: /resources/boards/:name.html
  learning_pathways:
    output: true
    permalink: /learn/learning_pathways/:name.html
  shortcuts:
    output: true
    permalink: :name.html
  groups:
    output: true
    permalink: /ideas/:name.html
  components:
    output: true
    permalink: /components/:name.html
  books:
    output: true
    permalink: /books/:name.html
  projects:
    output: true
    permalink: /projects/:name.html
  stem:
    output: true
    permalink: /stem/:name.html
  discover:
    output: true
    permalink: /discover/:name.html