title: KevsRobots
email: kevinmcaleer@gmail.com
description: This is the official website of Kevin McAleer
baseurl: ""
url: "http://www.kevsrobots.com"

markdown: kramdown
permalink: /blog/:title:output_ext

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

collections:
  rooms:
    output: true
    permalink: /museum/:collection/:name
  ptor:
    output: true
    permalink: /periodic-table-of-robotics/:name